### ISSUE TITLE
Highlighting non-generalizable test actions

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#11]
Go through the test plan and identify actions that cannot be generalized. And that would require their own function in "steps" module

**Comment by Smat26** [comment]
@bjafri5 
I have realised that following feature in Live Chat are non-generalizable.
1. Sending Gifs
2. Sending Stickers
3. Sending emoticons

**Comment by bjafri5** [comment]
Okay, I'll add these functions to the steps file.

**Comment by Smat26** [comment]
Sending all broadcast/poll/surveys templates is non-generalizable... or it would atleast require lots of steps to make writing a test case for it unduly lengthy.
