### ISSUE TITLE
Fix Front-end Issues that may impede Automated Testing

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#13]
Lack of Placeholder text in Polls and Workflows, prevents the testing script to be unable to find the input boxes where it can write. Fixing the front-end can allow these two things to be automated.

**Comment by jekram** [comment]
@Smat26  I am not understanding this. Please attach screenshot what the current screen is and what you wanted it changed.

**Comment by Smat26** [comment]
So there are various forms throughout our web application that are required to be filled.

The automated testing application does a very thorough  job of finding these input text boxes, and filling them in.

It does so by reading the Placeholder text on the text boxes, and knowing what to write in which of the many input boxes:

![image](https://user-images.githubusercontent.com/9948564/34666964-b1fe2262-f488-11e7-9a07-dd88eec58f4f.png)

It can identifiy each text box in the above screen, by the "placeholder value" that is present.
So the test application can write the responses via the following instructions:

```
1. Click on Response 1.
2. Write "Apple"
2. Click on Response 2.
3. Write "Mango"
etc etc..

```

However the actual Question of the Poll does not have any placeholder text, which makes it almost impossible to reference this text box in any way for the person designing the test steps.

This same problem is in workflows as well:

![image](https://user-images.githubusercontent.com/9948564/34667058-276a9102-f489-11e7-82ca-7625193c139b.png)


You can reference to any existing field. However the "Reply" field does not have a placeholder. Which again makes it impossible to reference it.

This issue is just about finding any such fields, and making sure that all text boxes have a relevant placeholder.

**Comment by Smat26** [comment]
Now after I have added the placeholder,

In Polls:

![image](https://user-images.githubusercontent.com/9948564/34668353-d8671e3a-f48e-11e7-982e-ded4e1dfa800.png)

In workflows:

![image](https://user-images.githubusercontent.com/9948564/34668388-f4919df6-f48e-11e7-8af5-0b615c4b0afe.png)
