### ISSUE TITLE
Making Function for each step

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#2]
Make a list of functions that are listed [here](https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=1683919152)

**Comment by bjafri5** [comment]
Following steps have been implemented:
wait,
open_kibopush,
login,
click_on,
press_enter,
logout,
sidebar_collapse,
sidebar_click,
write,
choose_select

**Comment by bjafri5** [comment]
This is now a duplicate of
#17
#18
#19
#20
#21
#22
So I'm closing this.
