### ISSUE TITLE
Implement functions for template functionality

### ISSUE THREAD

**Issue by bjafri5** [Cloudkibo/KiboPush_Automated_Testing#22]
Implement functions for predefined templates for broadcasts, surveys, and polls.

**Comment by bjafri5** [comment]
This is complete for broadcast templates. Surveys and Polls remain.

**Comment by bjafri5** [comment]
Testing of survey templates and polls depends on https://github.com/Cloudkibo/KiboPush/issues/1726

**Comment by jekram** [comment]
To make a modification to the product so we can do automated testing is not a good idea. The product should be developed independently of the test, else every time we make product modification the automated testing would break.

We need to find some other solution. Let's discuss this in the meeting.
@sojharo @bjafri5 @Smat26 

Options:
1. Why does it need to be empty? Program around it
2. What is the effort to implement #1726
3. Should we get a droplet to test

**Comment by Smat26** [comment]
Mentioning some other relevant issues I opened in this regard:
https://github.com/Cloudkibo/KiboPush/issues/1742
https://github.com/Cloudkibo/KiboPush/issues/1741

**Comment by bjafri5** [comment]
This is now complete for polls and broadcasts. Surveys remain.

**Comment by bjafri5** [comment]
This is now complete.
