### ISSUE TITLE
Enhancement to Automated Testing Script - Not testing unverified tests

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#28]
Automated Testing can do with lots of improvements considering now that there are bulk of operations and testing, and they are multiplied across the account types.

There are lots of failed tests because of the fact that testing even checks for tests which are unverified, which eats up a lot of time, and give a non-accurate result. We need to enhance automated testing, so it does not test for unverified test

**Comment by jekram** [comment]
I do not understand what enhancements are needed. Please explain what work will be done here.

Why do we make everything very complicated?

If we have Test 1 thru Test 10 for example, and test Test 5 and Test 6 are not needed. Is it not a simple thing to comment out or not run Test 5 and Test 6.

What programming is needed here to do this task?

**Comment by Smat26** [comment]
Ok. So there are two folds things to this problem:

1. Reader module reads the csv, and passes on information ahead. Now I would have to check for appropriate column on each test, the "Verified" Column, and based on it's data, it would send it forward.

2. It would require to make sure that this column is populated correctly in the Test Plan, so I would need to manually update that particular column as well.

**Comment by Smat26** [comment]
This has been completed
