### ISSUE TITLE
PDF Report Generation module

### ISSUE THREAD

**Issue by bjafri5** [Cloudkibo/KiboPush_Automated_Testing#29]
This module would generate a pdf report that would highlight the results of automated testing in a user-friendly format. This would generate a separate pdf for each account type.

**Comment by bjafri5** [comment]
Format of the report would be like this:

![image](https://user-images.githubusercontent.com/22233815/35948188-31bea190-0c8d-11e8-8645-53c2dbe122df.png)

Dependent on https://github.com/Cloudkibo/KiboPush_Automated_Testing/issues/30 for populating the data for the report.

**Comment by jekram** [comment]
We are making this all too difficult. I am not going to review this report on a daily basis.

The Test Plan needs to be populated and GitHub issues need to be created for ALL failed cases.

Mark the sheet N/A when we are not testing.

Mark all the failed with Data. Why it failed, Bug number, etc etc

If we do not understand. Ask me in the meeting.

I currently have zero visibility to the automated test.

**Comment by bjafri5** [comment]
The report would show which tests failed, and at which step.  This will make it easier to identify failed issues, which can then be manually opened up on Github, as well as updated on the test plan. I can explain in the meeting in more detail what this report will do.

**Comment by bjafri5** [comment]
I've updated the report to include status of all accounts on one document rather than separate documents for buyer, admin, agent, and individual:

![image](https://user-images.githubusercontent.com/22233815/36195389-21710218-118f-11e8-9c5d-0436023b79a9.png)

**Comment by jekram** [comment]
@bjafri5  Why is this still open? What is the next step?

Should this marked as "resolved"

**Comment by bjafri5** [comment]
This is complete. This can be closed
