### ISSUE TITLE
Generate data for reporter module

### ISSUE THREAD

**Issue by bjafri5** [Cloudkibo/KiboPush_Automated_Testing#30]
Mapper file would generate data to pass to the reporter module (https://github.com/Cloudkibo/KiboPush_Automated_Testing/issues/29). The reporter module would then use this to data to generate a report. 

Data should be in this format:

results_buyer = [
    {
        'test': '#1',
        'category': 'Sidebar',
        'description': 'Navigation',
        'steps': steps,
        'expected_results': 'User is routed to correct route for each element on the sidebar',
        'status': 'Failed',
        'remarks': 'Step 7 failed'
    },
    {
        'test': '#2',
        'category': 'Sidebar',
        'description': 'Navigation',
        'steps': steps,
        'expected_results': 'User is routed to correct route for each element on the sidebar',
        'status': 'Failed',
        'remarks': 'Step 7 failed'
    }
]

summary_buyer = {
  'tests_passed': 0,
  'tests_failed': 2,
  'failed_tests': [
    '#1','#2'
  ]
}

**Comment by jekram** [comment]
We need to finish the work at hand instead of creating more reports that does not provide any value.

**Comment by bjafri5** [comment]
The main issue with automated testing right now is that there isn't proper visibility as to what it is doing. This would help rectify that.

**Comment by Smat26** [comment]
I have partially implemented that, and some information is now being propagted. I would re-write reporter module now, to get the remaining information.

**Comment by bjafri5** [comment]
I've updated the reporter module https://github.com/Cloudkibo/KiboPush_Automated_Testing/issues/29#issuecomment-365538108

Data should be in this format:
results = [
      {
          'test': '#1',
          'category': 'Sidebar',
          'description': 'Navigation',
          'steps': steps,
          'expected_results': 'User is routed to correct route for each element on the sidebar',
          'buyer_status': 'Failed',
          'admin_status': 'Failed',
          'agent_status': 'Failed',
          'individual_status': 'Failed',
          'remarks': 'Step 7 failed'
      },
      {
          'test': '#2',
          'category': 'Sidebar',
          'description': 'Navigation',
          'steps': steps,
          'expected_results': 'User is routed to correct route for each element on the sidebar',
          'buyer_status': 'Failed',
          'admin_status': 'Failed',
          'agent_status': 'Failed',
          'individual_status': 'Failed',
          'remarks': 'Step 7 failed'
      },
  ]

**Comment by Smat26** [comment]
This has been completed.

**Comment by jekram** [comment]
When something can be closed Mark them as "Resolved". Are we done?
