### ISSUE TITLE
Persistent Messenger Button

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#31]
The Messenger Button that has been introduced can visually block the interface below, and Selenium may end up clicking atop the box.

![image](https://user-images.githubusercontent.com/9948564/35956553-63bcc2be-0cb8-11e8-845c-69c0e4a3dc58.png)

@jekram Are we going with the messenger pop up?
If yes, then we would need to implement this small functionality to minimize that pop up at each test.

**Comment by sojharo** [comment]
@dayemsiddiqui This button should also be on marketing website www.kibopush.com

in face it should always be there and here it should only show on login page and not in application itself. My opinion is that it should be on marketing website only.

**Comment by bjafri5** [comment]
I've implemented a function in Selenium that will close the messenger pop up: close_help_popup()
