### ISSUE TITLE
Integrate Persistent Menu

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#32]
This task would include adding implementation of Persistent Menu to Parser and Mapper.
And writing test cases accordingly for Persistent Menu

**Comment by Smat26** [comment]
I have integerated persistent menu functions with the testing application

**Comment by Smat26** [comment]
Blocked by #34

**Comment by jekram** [comment]
what is blocked #34 was fixed 19 days ago

**Comment by Smat26** [comment]
I couldn't pick this issue after that. I will look into this today

**Comment by jekram** [comment]
Please do this after automated test

**Comment by Smat26** [comment]
All the testcases have been re-written, and have been verified in debug mode.
Just one change required which would be done in #61

**Comment by Smat26** [comment]
This is now complete. It can be closed now.
