### ISSUE TITLE
Open Facebook Account after Test Completion

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#33]
After Automated Test has been conducted. We have to check for certain aspects of the tests manually by logging into the test accounts, and seeing whether the messenger have the required messages.

We can add a functionality to open Facebook Accounts of the Test Users, after test have been completed.

Details:
- The function for these would have to be implemented in steps.py
- It would accept the parameter of "type" (just like login), to open relevant fb account.
- Preferably the accounts would be on separate windows to prevent one account from logging the other out.

**Comment by bjafri5** [comment]
This is complete.
