### ISSUE TITLE
Updating Poll sending and creation

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#36]
Send/Save option have been added at Poll Creation:

![image](https://user-images.githubusercontent.com/9948564/36830640-51f7c8dc-1d46-11e8-94ff-83bc05ee3a40.png)

All relevant tests dealing with poll creation or sending need to be updated

**Comment by Smat26** [comment]
Have updated the test case. This is complete.
I just need to verify this next time I run my script

**Comment by jekram** [comment]
what is the status?
