### ISSUE TITLE
Updating Survey creation and sending

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#37]
Survey now have send/save option when we click on save.

All survey creation and sending tests have to be updated consequently.

![image](https://user-images.githubusercontent.com/9948564/36830768-d87c65c0-1d46-11e8-8f66-7ced79edc33d.png)

**Comment by Smat26** [comment]
Completed the change in test cases. Need to verify it at next script running.

**Comment by jekram** [comment]
where will this get fixed? in the product or in the test tool? What is the next step

**Comment by Smat26** [comment]
This has now been fixed in the actual test cases involving Polls and Survey.

**Comment by jekram** [comment]
Thanks
