### ISSUE TITLE
Send broadcast template function got broken

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#39]
There is a function to test whether all test broadcast are being sent, by looping through each, and sending it.

This function is now not working. It needs to be looked into.

**Comment by bjafri5** [comment]
This isn't broken. This is failing due to https://github.com/Cloudkibo/KiboPush/issues/2066

**Comment by Smat26** [comment]
Marking it as resolved.

**Comment by jekram** [comment]
I am assuming that we can run the test?
