### ISSUE TITLE
Sidebar hamburger failing

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#40]
The sidebar hamburger has been fixed by Dayem. However the changes would have caused the click point of clicks to have changed.

Report is showing collapsing and expanding as failed. The function needs to be changed according to Dayem's changes.

![image](https://user-images.githubusercontent.com/9948564/36857040-542b71dc-1d99-11e8-880d-f815099718b4.png)

**Comment by bjafri5** [comment]
I've fixed this.

**Comment by Smat26** [comment]
Tested. It is working

**Comment by jekram** [comment]
Thanks
