### ISSUE TITLE
Documenting the Function in Steps

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#44]
As Automated Testing have grown, so have the number of functions in our steps module.

The steps module is now approaching 50 unique functions.
There is a need to properly document this.

The function can be documented by simply adding a 'Docstring' to each function.
Ideally also add sample usage.

**Comment by jekram** [comment]
@bjafri5  What is the status?

**Comment by jekram** [comment]
@bjafri5  what is the update here?

**Comment by bjafri5** [comment]
I'll be working on completing this by today

**Comment by jekram** [comment]
@bjafri5 The status should be what was done yesterday, what will be done today?

**Comment by bjafri5** [comment]
This is complete

**Comment by Smat26** [comment]
I went through this, and reviewed the documentation. 
Marking it as resolved.

**Comment by jekram** [comment]
Publish this on the Wiki

**Comment by Smat26** [comment]
@jekram I have published the documentation to the wiki here:
https://github.com/Cloudkibo/KiboPush_Automated_Testing/wiki/Steps-Module
