### ISSUE TITLE
Restructuring the Repository

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#45]
We should aim for a proper folder structure hierarchy.
As of right now, all things are dumped in the utils folder.

We have to properly update the folder structure by doing:

1. Move all "upload files" into "Uploads" folder, at the root of the repo. Make appropriate changes in Steps.py
2. Move all generated logs to "logs" folder, at the repo's root. Make appropriate changes in the log.py
3. Move test_plan to "Test_Plan" Folder, and make appropriate changes in reader.py (in name variable)
4. Centrally untrack pyc file and .env folder. So they don't show up on github

**Comment by bjafri5** [comment]
This is complete.

**Comment by Smat26** [comment]
Oh there was one thing I missed above.
5. Add a requirement.txt file.

**Comment by Smat26** [comment]
Also one little thing.
Put Logs folder on ignore as well. It shows up on "git status".

**Comment by bjafri5** [comment]
I have made the changes.

**Comment by jekram** [comment]
@Smat26 Please test this

**Comment by jekram** [comment]
@bjafri5 when you want somebody to test it. it is up to the developer to contact the tester on slack and assign it in the GitHub

@sojharo FYI

**Comment by Smat26** [comment]
Tested. All the above has been done.
