### ISSUE TITLE
Broadcast clicking on "Enter your Text"

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#46]
![image](https://user-images.githubusercontent.com/9948564/36992384-8cef3842-20cc-11e8-89bd-b0019a1af329.png)

The test is failing due to the fact that click_on is not working "Enter your text".
This needs to be looked into.

**Comment by bjafri5** [comment]
I've fixed this.

**Comment by Smat26** [comment]
Check the latest report. Now there is click-send issue.
[report (1).pdf](https://github.com/Cloudkibo/KiboPush_Automated_Testing/files/1783652/report.1.pdf)

**Comment by jekram** [comment]
what is the next step here?

**Comment by Smat26** [comment]
@jekram we just need to fix the affected function.

@bjafri5 This is happening in "Sending link test":

![image](https://user-images.githubusercontent.com/9948564/37074366-41601ca2-21ee-11e8-90b2-b7bd1d8bdeaa.png)

**Comment by jekram** [comment]
This one says Code complete? If you are finding the bug then you need to remove "code complete".

**Comment by Smat26** [comment]
This is now working. Marking it as resolved.
