### ISSUE TITLE
Autoposting "Add Channel" to "Add Feed"

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#47]
The button in Autoposting was previously
"Add Channel". Now it is "Add Feed".

The test cases has to be changed for this.

**Comment by Smat26** [comment]
done

**Comment by jekram** [comment]
Is this more important than overall test plan?

when things are tested please make them "resolved"

**Comment by Smat26** [comment]
This is part of the test plan.

If we don't fix affected test cases, then they would be failing over minor reasons like this.

**Comment by jekram** [comment]
is this done and can be closed? please mark it resolved
