### ISSUE TITLE
Issue with sending Gallery in broadcast

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#49]
Due to changes. Sending Gallery broadcast is not working as it should be. There is issue with adding the button.
Gallery tests are failing as a result.
However Gallery is working in actual.

![image](https://user-images.githubusercontent.com/9948564/37074002-25450b06-21ec-11e8-975b-98c31ca4ab54.png)

**Comment by jekram** [comment]
@Smat26 was it working before and why it broke?

**Comment by Smat26** [comment]
Sending Galleries had been one of the earliest thing we automated. So yes. It was working.

This most likely broke since last changes Dayem did to the gallery.

**Comment by jekram** [comment]
Ok

**Comment by bjafri5** [comment]
I've fixed this. Please test @Smat26

**Comment by Smat26** [comment]
I ran the broadcasts test through Automated Testing tool to verify this.

It ended up finding a genuine bug (I have already opened relevant issue):

![29_admin_click_on](https://user-images.githubusercontent.com/9948564/37362489-23444d5a-2717-11e8-9473-6e6d14efd858.png)

So function is breaking at: 
![image](https://user-images.githubusercontent.com/9948564/37362578-682c6e70-2717-11e8-92d2-0ba90c9bd994.png)

As this is not the same step, therefore I assume this has been successfully resolved.
