### ISSUE TITLE
Make Test Accounts for automated Testing

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#5]
We would need to ceate Facebook test users account, that would be utilized for the actual testing.
These test accounts would need to have pages and subscribers to them and they should be manually integrated with KiboPush.

**Comment by Smat26** [comment]
This task was critical to actually testing out the cases. 
So I have made the test accounts myself, and I have hard coded the credentials in the code.

**Comment by jekram** [comment]
Thanks
