### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#50]
The file is not uploading for broadcast.
This has been manually verified to be working, so it is an issue with automated testing.

![image](https://user-images.githubusercontent.com/9948564/37074264-c5f4461a-21ed-11e8-8941-8ec750058cbd.png)

**Comment by jekram** [comment]
@Smat26 Why this script is not working now? Was it working before?

**Comment by Smat26** [comment]
It was definitely working before.
I will let you know the exact reason, once I have looked into it today.

**Comment by Smat26** [comment]
This is now working.
Marking it as resolved.
