### ISSUE TITLE
Cannot find "Create Survey" in Template

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#52]
The script cannot find Create Survey, after it clicks on "Edit Template".
Manually verified to work

![image](https://user-images.githubusercontent.com/9948564/37074934-13e7e87e-21f1-11e8-9c38-57a278283bd2.png)

**Comment by jekram** [comment]
@Smat26 Was this working before? What makes it not work now?

**Comment by Smat26** [comment]
Yes. It was working before.

It is just unable to find that "Create Survey" Button. And I have yet to debug, why that is actually so.

**Comment by Smat26** [comment]
This is working. Marking it as resolved.
