### ISSUE TITLE
Need to add placeholder in "Add Poll Template"

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#53]
Need to put placeholder to allow script to work here

![image](https://user-images.githubusercontent.com/9948564/37076190-504da62c-21f7-11e8-9342-113a360db854.png)

**Comment by jekram** [comment]
@Smat26  What is the next step here?

**Comment by Smat26** [comment]
I am assigning this to myself.

**Comment by jekram** [comment]
what is the update here?

**Comment by Smat26** [comment]
I have completed this.
