### ISSUE TITLE
Ability to run only specific tests

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#54]
When fixing broken tests, it's far convenient and quicker, if we can parametrize the script, such that it gives the user option to run

1. A particular section only
2. Ability to run only failed tests in Test Plan.
3. Ability to run for specific user types only

The way script is, it simply fetches all of the test plan, and tests for everything.
Which can make things unnecessarily time consuming.

**Comment by Smat26** [comment]
Completed. @bjafri5 if you have tested it out. Mark it as resolved.

**Comment by jekram** [comment]
Thanks
