### ISSUE TITLE
Screenshot Functionality

### ISSUE THREAD

**Issue by bjafri5** [Cloudkibo/KiboPush_Automated_Testing#55]
Implement functionality to take a screenshot. This will be used to take a screenshot every time a step fails so that it can be easily viewed later. The recent broken functionality is hard to reproduce in isolation, so this would help in retracing the problem.

**Comment by bjafri5** [comment]
This is complete.

**Comment by Smat26** [comment]
Marking it as resolved.

**Comment by jekram** [comment]
Thanks
