### ISSUE TITLE
Send Broadcast Template function

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#57]
The UI for Edit Broadcast Template has changed, so implementation of "send_broadcast_templates" need to be revised in our steps.py

@bjafri5 I think it might be fixed by just adding "click_on-Next" before we send the broadcast.

**Comment by bjafri5** [comment]
I've fixed this. @Smat26 please test

**Comment by Smat26** [comment]
tested. THis is working. 
Marking it as resolved.
