### ISSUE TITLE
Write Reader  module

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#6]
Module to read test plans, and sanitize and fetch the test steps

**Comment by Smat26** [comment]
I have completed this module.
It reads from the test plan, and sanitizes data for the next module i.e. Parser

**Comment by jekram** [comment]
are we done with this task?

**Comment by Smat26** [comment]
Yes

**Comment by jekram** [comment]
Should we close this task?

**Comment by jekram** [comment]
Please mark them resolved. In the future
