### ISSUE TITLE
Placeholder required in Persistent Menu

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#60]
When adding web url, there is no placeholder on the textbox.

![image](https://user-images.githubusercontent.com/9948564/37257305-9ffb45f4-2589-11e8-981f-a5482c60d55c.png)

**Comment by jekram** [comment]
what is the update here?

**Comment by bjafri5** [comment]
I've fixed this:

![image](https://user-images.githubusercontent.com/22233815/37461974-17ca2e3e-2872-11e8-8315-c50b8a807829.png)

**Comment by Smat26** [comment]
Tested. Marking this as resolved.
