### ISSUE TITLE
Testing on cases, which are specific to roles

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#65]
Right now roles can get tested on Test Cases which they are not supposed to be tested on, resulting in bloated number of "Failed" Tests. This can be avoided by inverting the status of tests, which do not apply to  the role.

Steps needed to achieve this are:
1. Adding a column in test plan to identify which roles it is applicable on.
2. Adding logic in the testing script to invert such results.

**Comment by jekram** [comment]
@Smat26 what is the status

**Comment by Smat26** [comment]
This has been partially completed.

I have done no.1,  that is, I have updated the Test Plan with a new column.

I am midway no.2, which is adding logic to the testing script to invert result

**Comment by Smat26** [comment]
This has been completed. Marking it as resolved.
