### ISSUE TITLE
Automating Signup

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#67]
We need to automate the procedure for sign-up, to the point user connects his facebook.

**Comment by jekram** [comment]
https://docs.google.com/document/d/1rNTn26qJ8rFNrFWQ_77Q2zg7DlBBJ0DluGEyYYulAnU/edit

**Comment by jekram** [comment]
@Smat26 

Please see my comments.

Overall we should keep it very simple. We should try to ditto the manual process and not create automation beyond it.

@sojharo Please also review

**Comment by sojharo** [comment]
I think easy thing would be to bypass the need of having verification email for test accounts. Because we already know that this emails belongs to us. We would put flag and it would know that this is test account and would just bypass the email verification. This would be easier than the procedures discussed above as these procedures provide less value comparing to the hard work that would be done to implement them.

**Comment by sojharo** [comment]
I have carefully reviewed the document. I couldn't understand the first point in the following points:

> **1. Test Servers:**
It would be like what we discussed. We ran an instance of a new server, and with that, we would trying testing out our sign-up procedures.

Are you saying that we should do something like docker containers and we should recreate our server instance each time we run the test? I think this approach is not good for testing as it would create more work of dealing with certificates and other things like this.

In my above comment, I have given one easy solution for this, which is to bypass the email verification for test account. i.e. during creating a test account server can bypass the need to verify the email address. Our testing environment should not be made more complex. Adding email servers and things like this will increase the burden of maintaining the stuff that we don't really need.

Other option is that you should have a separate database within staging or production called "kibopush-test". This would be used solely for you and at the end you should empty it. So, I agree with your third point that we should have clear the database after test is run.

Until we have this query to clear entire database, please manually empty the database tables. It won't take more than a minute from robomongo.

**Comment by sojharo** [comment]
Please see my final summary in the document:

https://docs.google.com/document/d/1rNTn26qJ8rFNrFWQ_77Q2zg7DlBBJ0DluGEyYYulAnU/edit

**Comment by jekram** [comment]
@Smat26  What is the update here. @sojharo has provided you detailed instructions.
