### ISSUE TITLE
Persistent Menu Test Cases

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#68]
The persistent Menu is saved when testing is being done. There is no way to remove a persistent Menu as of yet.
Therefore in the next test run, the previous persistent menu, conflict with the newer one. and some test cases fail as a result. 

This needs to be fixed.

**Comment by jekram** [comment]
What is the plan to fix this?

**Comment by Smat26** [comment]
Properly fixing this is dependent on:
https://github.com/Cloudkibo/KiboPush/issues/1742
