### ISSUE TITLE
Add waits before assertions

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#69]
Before we verify an alert, or a table, we now need to explicitly wait for it to happen.

This is affection following cases in the [report](https://cloudkibo.slack.com/files/U9MH8B3C5/FA0SA0WPJ/report.pdf):

- 28
- 31
- 32
- 34
- 36
- 47

**Comment by jekram** [comment]
@Smat26  What is the status here?

describe what these are: (the number do not mean any thing)

28
31
32
34
36
47
