### ISSUE TITLE
Write Parser Module

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#7]
The parser module would convert the written steps into actual Actions.

**Comment by Smat26** [comment]
I have partially completed this.
The parser is able to parse any specified step into a simple action,
I will now work on parsing the more complex steps into an action.

**Comment by Smat26** [comment]
This has been completed.

**Comment by jekram** [comment]
Should we close the task?

**Comment by Smat26** [comment]
Yes. This can be closed
