### ISSUE TITLE
Automate test cases for broadcasts from revised test plan

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/KiboPush_Automated_Testing#71]
This task is to automate test cases for broadcasts. There are 70+ test cases which need to be automated. We will automate every test cases one by one and report here daily.

Revised Test Plan (sheet10):
https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=25812408

**Comment by bjafri5** [comment]
TC0106 - TC0123 have been automated

TC0124 - TC0204 remain

**Comment by jekram** [comment]
Thanks this is good progress.

@bjafri5  I am assuming that we are using the new tool to automate these?

Since it is a client side. Can we export your work and share with other teams members

@ImranBinShoukat @sojharo @arveenkumar55

**Comment by bjafri5** [comment]
Yes, I'm using the new tool to automate the test cases.

I'm attaching the current work that contains the automated test cases:

[KiboPush.zip](https://github.com/Cloudkibo/KiboPush_Automated_Testing/files/2265096/KiboPush.zip)

This can be imported into Katalon Studio. I will look into git integration so that changes can be directly pushed to this repo. 

TC0106 - TC0139 have been automated 

TC0140 - TC0204 remain

Following tests failed during automated testing. I have opened the relevant issues in the KiboPush repo:
TC0120 (https://github.com/Cloudkibo/KiboPush/issues/4102)
TC0124 and TC0125 (https://github.com/Cloudkibo/KiboPush/issues/4101)
TC0133 (https://github.com/Cloudkibo/KiboPush/issues/4100)

**Comment by bjafri5** [comment]
TC0106 - TC0150 have been automated
TC0151 - TC204 remain

**Comment by bjafri5** [comment]
TC0106 - TC0175 have been automated
TC0176 - TC204 remain

**Comment by bjafri5** [comment]
TC0106 - TC193 has been automated
TC194 - TC204 remain

95% of broadcast test cases have been automated. The rest will be complete by today.

**Comment by bjafri5** [comment]
This is complete. All of broadcast test cases have been automated.

**Comment by jekram** [comment]
@bjafri5  Should be resolved and we should close this?

**Comment by jekram** [comment]
@bjafri5  What is the update here for: TC0258 - TC0291

**Comment by bjafri5** [comment]
Yes, this can be closed. Here is the result of the last run of automated tests for broadcasts:
[KiboPush_Broadcasts_Test_Results.pdf](https://github.com/Cloudkibo/KiboPush_Automated_Testing/files/2289304/KiboPush_Broadcasts_Test_Results.pdf)

TC0258 - TC0291 is being managed in this issue: https://github.com/Cloudkibo/KiboPush_Automated_Testing/issues/78

**Comment by ImranBinShoukat** [comment]
I have reviewed the test cases.
1. TC0204 and TC0126 are incomplete. @bjafri5 please complete them
2. Test cases related to pagination are not implemented properly. Here, we should compare the dates of every page instead of just checking whether they are not equal.
3. Test cases related to search are also not implemented properly. Here, we should check whether title contains the text or not instead of checking whether it is equal to the title.

**Comment by bjafri5** [comment]
I've made the requested changes

**Comment by ImranBinShoukat** [comment]
Reviewed. The changes have been implemented. @bjafri5 please do one more thing. Recently, @arveenkumar55 has written test cases for list. Please incorporate them as well.

**Comment by jekram** [comment]
@ImranBinShoukat  Is this done and should we close this

**Comment by ImranBinShoukat** [comment]
No sir this is not done. Test cases for list are remaining here.

**Comment by bjafri5** [comment]
Test cases for list have been automated

**Comment by ImranBinShoukat** [comment]
Reviewed.

**Comment by jekram** [comment]
thanks
