### ISSUE TITLE
Understand KiboPush_Automated_Testing code

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/KiboPush_Automated_Testing#72]
This task is to sit with Baqar and understand KiboPush_Automated_Testing code.

**Comment by arveenkumar55** [comment]
I am installing setup of Katlan studio but currently there is no gui version of katlon studio on Linux. so now i am installing virtual box to install windows and will do all testing setup on windows.
![katlon studio](https://user-images.githubusercontent.com/39855662/43758374-579f34f2-9a35-11e8-9f66-289910b4a795.png)

**Comment by arveenkumar55** [comment]
I have just download virtual box and install on ubuntu and i haven't windows setup in office so i will get setup from home and install tomorrow in office PC.

**Comment by jekram** [comment]
@arveenkumar55  Is there not a desktop available for you in the office with Windows on it?

@sojharo

**Comment by jekram** [comment]
@arveenkumar55  Are we done with this?

**Comment by arveenkumar55** [comment]
I have done All setup on office laptop and understood how to write test cases from baqar. sojhro assigned me today for manual testing of production because sojhro merged code form staging to production. I will start Automating testing from tomorrow.

**Comment by arveenkumar55** [comment]
I have completed this issue.
