### ISSUE TITLE
Research and Discuss Katalon Studio tool

### ISSUE THREAD

**Issue by bjafri5** [Cloudkibo/KiboPush_Automated_Testing#74]
This issue is to document the discussion and usage of the Katalon Studio tool 

Here is the writeup on the overview and primary advantages of this tool:
https://docs.google.com/document/d/1vRRKX052J0805lBa1PAIkvG1G4hmf3M0PucmyczUjSk

@jekram

**Comment by jekram** [comment]
Thanks @ImranBinShoukat @bjafri5  Great job
