### ISSUE TITLE
Automate test cases for surveys from revised test plan

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/KiboPush_Automated_Testing#75]
This task is to automate test cases for surveys. There are 50+ test cases which need to be automated. We will automate every test cases one by one and report here daily.

Revised Test Plan (sheet10):
https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=25812408

**Comment by arveenkumar55** [comment]
Today I have written test cases from TC0205--------->TC0225(Servey Menu testcases) . Remaining Test Cases will write tomorrow or coming Monday.

**Comment by jekram** [comment]
Thanks.

Prefer also to know a summary % complete

**Comment by arveenkumar55** [comment]
I have completed all test-cases of servey except two test-cases(TC0240,TC0241). I have confusion in  two cases which will discuss with imran and baqar on coming Monday. 
95% test-cases of servey completed.

**Comment by jekram** [comment]
Thanks. I am more interested in % of overall cases automated vs just survey

**Comment by arveenkumar55** [comment]
Today I have completed all servey test cases.

**Comment by jekram** [comment]
Thanks

**Comment by jekram** [comment]
GREAT JOB. THANKS

**Comment by jekram** [comment]
@arveenkumar55  update please

**Comment by arveenkumar55** [comment]
This task is complete. Now i am doing automate test cases of Polls issue no #78

**Comment by ImranBinShoukat** [comment]
I have reviewed the test cases. 
1. TC0208 is not complete. Here, we should compare the dates also.
2. Test cases related to pagination are not implemented properly. Here, we should compare the dates  instead of just checking whether they are not equal.

**Comment by arveenkumar55** [comment]
I have made changes.

**Comment by ImranBinShoukat** [comment]
Reviewed.

**Comment by jekram** [comment]
Thanks
