### ISSUE TITLE
Integrate Git With Katalon Studio

### ISSUE THREAD

**Issue by bjafri5** [Cloudkibo/KiboPush_Automated_Testing#76]
This task is to look into git integration and integrate git with Katalon Studio so that changes/additions with the test scripts can be pushed and pulled from this repo

**Comment by bjafri5** [comment]
This is complete.

How to run the test cases:
1. Pull/Clone this repository to your local machine
2. Within Katalon Studio, File > Open Project
3. Select the KiboPush Katalon folder
4. Select a Test Suite:
<img width="1280" alt="screen shot 2018-08-13 at 10 15 53 am" src="https://user-images.githubusercontent.com/22233815/44013925-20cc564c-9ee2-11e8-9fbb-2d0779abffb1.png">
5. Run the Test Suite:
<img width="1280" alt="screen shot 2018-08-13 at 10 15 55 am" src="https://user-images.githubusercontent.com/22233815/44013931-281a2564-9ee2-11e8-881b-e56dfd9a6469.png">

**Comment by jekram** [comment]
@bjafri5  @sojharo  How do we share this to other?

**Comment by bjafri5** [comment]
Pull/Clone or download the zip folder of this repository to your local machine. Within the folder, there will be a folder named 'KiboPush Katalon'. This folder can be imported into Katalon Studio as well as shared with others so that they can import it into Katalon Studio.

**Comment by jekram** [comment]
@bjafri5  You need to communicate this rest of team members or slack or on KB article

@sojharo
