### ISSUE TITLE
Automate test cases for live chat from revised test plan

### ISSUE THREAD

**Issue by bjafri5** [Cloudkibo/KiboPush_Automated_Testing#77]
This task is to automate test cases for live chat. There are 70+test cases which need to be automated. We will automate every test case one by one and report here daily.

Revised Test Plan (sheet10):
https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=25812408

@ImranBinShoukat

**Comment by bjafri5** [comment]
TC0292 - TC0309 have been automated.
25% of live chat test cases are complete.

**Comment by bjafri5** [comment]
TC0292 - TC0309 have been automated (~25% of live chat test cases)

**Comment by bjafri5** [comment]
TC0292 - TC0322 have been automated (~45% of live chat test cases)

**Comment by bjafri5** [comment]
TC0292 - TC0338 have been automated (~65% of live chat test cases)

**Comment by bjafri5** [comment]
This is complete.

**Comment by ImranBinShoukat** [comment]
I have reviewed it. @bjafri5 some test cases are not implemented correctly. Please look into them.

**Comment by bjafri5** [comment]
This is complete

**Comment by ImranBinShoukat** [comment]
Reviewed.

**Comment by jekram** [comment]
Thanks @ImranBinShoukat @bjafri5
