### ISSUE TITLE
Automate test cases for polls from revised test plan

### ISSUE THREAD

**Issue by sojharo** [Cloudkibo/KiboPush_Automated_Testing#78]
This task is to automate test cases for polls. There are 50+ test cases which need to be automated. We will automate every test cases one by one and report here daily.

Revised Test Plan (sheet10):

https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=25812408

**Comment by arveenkumar55** [comment]
Today I have completed test cases from TC0257-----> TC0267 .

**Comment by arveenkumar55** [comment]
Today i have completed all test cases of Polls.
100% completed  test cases of Polls.

**Comment by arveenkumar55** [comment]
@ImranBinShoukat  kindly test this issue.

**Comment by jekram** [comment]
Thanks
