### ISSUE TITLE
Automate test cases for Login, Signup, Forgot Password, and Wizard

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/KiboPush_Automated_Testing#79]
This task is to automate test cases for following:
1. Login (09 test cases)
2. Signup (10 test cases)
3. Forgot Password (3 test cases)
4. Wizard (31 test cases)

Test plan document:
https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=25812408

**Comment by arveenkumar55** [comment]
I have completed Login, Signup, Forgot Password testcases.

**Comment by jekram** [comment]
Thanks for the update

**Comment by arveenkumar55** [comment]
Completed all Test cases of wizard.

**Comment by ImranBinShoukat** [comment]
Reviewed.

**Comment by jekram** [comment]
thanks
