### ISSUE TITLE
Write Report Module

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#8]
Once the tests has been performed, there should be a report module that publish all statistics regarding each test.
Including but not limited to:
1. Unclear test steps 
2. Total Pass or Fail
3. Remarks
4. Screenshot

**Comment by bjafri5** [comment]
Closing due to https://github.com/Cloudkibo/KiboPush_Automated_Testing/issues/29

**Comment by jekram** [comment]
The process is that I should only I should close the task. You should mark it resolved and describe what was done.

What was done here to close this task?

We have open another task is that the effort?

**Comment by bjafri5** [comment]
I've updated this task with #29 as it is a duplicate.
