### ISSUE TITLE
Automate test cases for Autoposting

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/KiboPush_Automated_Testing#80]
This task is to automate test cases for autoposting. There are 26 test cases which need to be automated.

Revised Test Plan (sheet10):
https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=25812408

**Comment by arveenkumar55** [comment]
I have completed 80% remaining will complete today.

**Comment by arveenkumar55** [comment]
I couldn't continue that issue yesterday because there is a bug in Auto posting when it will remove i will start my work.

**Comment by arveenkumar55** [comment]
completed testcases.

**Comment by jekram** [comment]
Thanks. What is next step

**Comment by ImranBinShoukat** [comment]
Reviewed. @arveenkumar55 4 test cases are remaining here. Please complete them also.

**Comment by arveenkumar55** [comment]
Completed testcases. kindly @ImranBinShoukat  review these testcases.

**Comment by ImranBinShoukat** [comment]
Reviewed.

**Comment by jekram** [comment]
Thanks
