### ISSUE TITLE
Automate test cases for comment capture

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/KiboPush_Automated_Testing#82]
This task is to automate test cases for comment capture. There are 20 test cases which need to be automated.

Revised Test Plan (sheet10):
https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=25812408

**Comment by arveenkumar55** [comment]
Completed 90% testcases yesterday. Remaining will complete today.

**Comment by arveenkumar55** [comment]
Completed testcases.

**Comment by ImranBinShoukat** [comment]
Reviewed. @arveenkumar55 2 test cases are remaining here. 
1. Test video tutorial (TC0506)
2. Choose page (TC0515)

Number 1 can't be automated right now as we have not integrated the video in our UI. Please complete TC0515. After that, I'll block this issue for TC0506.

**Comment by arveenkumar55** [comment]
Completed testcases.

**Comment by arveenkumar55** [comment]
@ImranBinShoukat  kindly review theses tescases.

**Comment by ImranBinShoukat** [comment]
Reviewed.
