### ISSUE TITLE
Automate test cases for header

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/KiboPush_Automated_Testing#83]
This task is to automate test cases for header. There are 21 test cases which need to be automated.

Revised Test Plan (sheet10):
https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=25812408

**Comment by arveenkumar55** [comment]
Completed TestCases.

**Comment by jekram** [comment]
what is the next step? is this resolved and can we close it?

**Comment by ImranBinShoukat** [comment]
Reviewed. 13 out of 21 test cases are completed. 

The remaining 8 test cases are related to advanced mode but we have removed the advanced mode and change it to UI mode. That's why they have not been implemented. 

@arveenkumar55 please replace advanced mode test cases with UI mode and then automate them as well.

**Comment by arveenkumar55** [comment]
Done. @ImranBinShoukat  kindly review these tescases

**Comment by ImranBinShoukat** [comment]
Reviewed.
