### ISSUE TITLE
Automate test cases for sidebar

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/KiboPush_Automated_Testing#84]
This task is to automate test cases for sidebar. There are 26  test cases which need to be automated.

Revised Test Plan (sheet10):
https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=25812408

**Comment by arveenkumar55** [comment]
Completed 30% testcases today.

**Comment by ImranBinShoukat** [comment]
Reviewed.

**Comment by jekram** [comment]
Thanks
