### ISSUE TITLE
Automate test cases for pages

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/KiboPush_Automated_Testing#86]
This task is to automate test cases for pages. There are 15 test cases which need to be automated.

Revised Test Plan (sheet10):
https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=25812408

**Comment by arveenkumar55** [comment]
Completed testCases.

**Comment by arveenkumar55** [comment]
@ImranBinShoukat  kindly test these cases.

**Comment by ImranBinShoukat** [comment]
Reviewed.
