### ISSUE TITLE
Automate test cases for invite members

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/KiboPush_Automated_Testing#87]
This task is to automate test cases for invite members. There are 11 test cases which need to be automated.

Revised Test Plan (sheet10):
https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=25812408

**Comment by arveenkumar55** [comment]
Completed testcases. @ImranBinShoukat  kindly  test these testcases

**Comment by jekram** [comment]
Thanks
