### ISSUE TITLE
Automate test cases for teams control

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/KiboPush_Automated_Testing#90]
This task is to automate test cases for teams control. There are only 4 test cases which need to be automated.

Revised Test Plan (sheet10):
https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=25812408

**Comment by Mehrish-Yousuf** [comment]
I have automated test cases but I those are failing because live chat is not working currently.

**Comment by jekram** [comment]
what is the open case for live chat?

**Comment by Mehrish-Yousuf** [comment]
https://github.com/Cloudkibo/KiboPush/issues/4319

**Comment by jekram** [comment]
How many test cases got implemented and how many pending?

**Comment by Mehrish-Yousuf** [comment]
I have implemented four test cases. Those four could be automated rest can not be.

**Comment by jekram** [comment]
@Mehrish-Yousuf  Can we follow the process? If this is done then why it it is not marked resolved?

**Comment by Mehrish-Yousuf** [comment]
Because those test cases can not be marked complete as they have dependency on live chat and live chat is not working properly on staging. That is why I have not marked this issue as resolved.

**Comment by jekram** [comment]
Mehrish: Why it was marked as "Done" in the deck. I do not read minds.
