### ISSUE TITLE
Automate test cases for smart replies

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/KiboPush_Automated_Testing#92]
This task is to automate test cases for smart replies. There are 33 test cases which need to be automated.

Revised Test Plan (sheet10):
https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=25812408

**Comment by Mehrish-Yousuf** [comment]
I am working on this issue. I have automated around 8 test cases so far. There are 33 test cases for this feature.

**Comment by Mehrish-Yousuf** [comment]
I have automated around 22 Test cases for this. For the remaining I need to check whether those can be automated or not. I will update the sheet accordingly.

**Comment by ImranBinShoukat** [comment]
Reviewed.

**Comment by jekram** [comment]
Thanks
