### ISSUE TITLE
Automate test cases for persistent menu

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/KiboPush_Automated_Testing#95]
This task is to automate test cases for persistent menu. There are 83 test cases which need to be automated.

Revised Test Plan (sheet10):
https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=25812408

**Comment by jekram** [comment]
@Mehrish-Yousuf  What is the update here?

**Comment by Mehrish-Yousuf** [comment]
I have automated around 30 Test cases for this.

**Comment by jekram** [comment]
how many pending?

**Comment by Mehrish-Yousuf** [comment]
I have automated 35 more. now 13  test cases are remaining.

**Comment by Mehrish-Yousuf** [comment]
I have completed test cases for this. assigning to @ImranBinShoukat to review.

**Comment by jekram** [comment]
thanks

**Comment by ImranBinShoukat** [comment]
Reviewed.

**Comment by jekram** [comment]
thanks
