### ISSUE TITLE
Automate test case for templates

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/KiboPush_Automated_Testing#96]
This task is to automate test cases for templates. There are 157 test cases which need to be automated. We don't have to write new test cases for broadcasts related tests. For this please utilize the broadcasts test cases and make them composite test cases.

Revised Test Plan (sheet10):
https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=25812408

**Comment by arveenkumar55** [comment]
completed 95 test cases. Remaining will complete tomorrow.

**Comment by jekram** [comment]
Great job Arveen. THANKS

**Comment by arveenkumar55** [comment]
Completed 40 test cases today.

**Comment by arveenkumar55** [comment]
@ImranBinShoukat  kindly review these testcases.

**Comment by ImranBinShoukat** [comment]
Reviewed.
