### ISSUE TITLE
automate test cases for settings.

### ISSUE THREAD

**Issue by sojharo** [Cloudkibo/KiboPush_Automated_Testing#98]
This task is to automate test cases for settings. There are 43 test cases which need to be automated. We don't have to write new test cases for broadcasts related tests. For this please utilize the broadcasts test cases and make them composite test cases.

Revised Test Plan (sheet10):
https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=25812408

**Comment by arveenkumar55** [comment]
kindly review these testcases.

**Comment by ImranBinShoukat** [comment]
Reviewed.
